### ISSUE TITLE
Code is bad

### ISSUE THREAD

**Issue by marceloneil** [curtischong/contest#1]
This code is bad. It takes too long to compile. To many words.

:(

**Comment by curtischong** [comment]
Judges evaluate the runtime of the program and don't take compile time into account. Modern cpp compilers are amazing at optimization so some of my slower scripts are most likely due to poor path prediction during loops and general poor approaches

**Comment by curtischong** [comment]
lol nvm. I didn't look at your pull request before commenting^

**Comment by marceloneil** [comment]
wow get out of here with your logic

**Comment by curtischong** [comment]
wait nvm I have to revert the pull bc I didn't anticipate the scope of the compression :s

**Comment by marceloneil** [comment]
Yeah, it really doesn't work at all (comments don't work). You can just revert the commit. The script is great though :)
